{
    "data": [
        {
            "user_id": 3,
            "name": "Aarav Sharma",
            "email": "emp1@gmail.com",
            "phone": "8765432001",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": 1,
            "shift_name": "Night shift",
            "duty_point_id": 1,
            "duty_point_name": "YSK 1",
            "from_date": "2025-06-29",
            "to_date": "2025-07-11",
            "status": "off_duty"
        },
        {
            "user_id": 4,
            "name": "Aditi Patel",
            "email": "emp2@gmail.com",
            "phone": "8765432002",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": 2,
            "shift_name": "Morning",
            "duty_point_id": 1,
            "duty_point_name": "YSK 1",
            "from_date": "2025-06-29",
            "to_date": "2025-07-11",
            "status": "on_duty"
        },
        {
            "user_id": 5,
            "name": "Akash Kumar",
            "email": "emp3@gmail.com",
            "phone": "8765432003",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 6,
            "name": "Ananya Singh",
            "email": "emp4@gmail.com",
            "phone": "8765432004",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 7,
            "name": "Arjun Gupta",
            "email": "emp5@gmail.com",
            "phone": "8765432005",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 8,
            "name": "Asha Reddy",
            "email": "emp6@gmail.com",
            "phone": "8765432006",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 9,
            "name": "Ayush Verma",
            "email": "emp7@gmail.com",
            "phone": "8765432007",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 10,
            "name": "Bhavya Jain",
            "email": "emp8@gmail.com",
            "phone": "8765432008",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 11,
            "name": "Chitra Nair",
            "email": "emp9@gmail.com",
            "phone": "8765432009",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        },
        {
            "user_id": 12,
            "name": "Deepak Yadav",
            "email": "emp10@gmail.com",
            "phone": "8765432010",
            "role": "Employee",
            "department_id": 1,
            "department_name": "Health Department",
            "shift_id": "",
            "shift_name": "",
            "duty_point_id": "",
            "duty_point_name": "",
            "start_time": "",
            "end_time": "",
            "from_date": "",
            "to_date": "",
            "status": "not_assigned"
        }
    ],
    "pagination": {
        "total": 20,
        "page": 1,
        "limit": 10,
        "totalPages": 2
    }
}